version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    networks:
      - app-network

  backend:
    # Usará o back-end/Dockerfile (que agora é o de produção)
    build: ./back-end
    container_name: backend-service
    ports:
      - "${API_PORT}:${API_PORT}"
    # VOLUMES REMOVIDOS: Em produção, o código não deve ser alterado em tempo real.
    environment:
      - NODE_ENV=production # Importante definir o ambiente para produção
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - FRONTEND_URL=${FRONTEND_URL}
      - PORT=${API_PORT}
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build:
      context: ./front-end
      # ADICIONE ESTA SEÇÃO 'args'
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: frontend-service
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local